/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javastatemachine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        StateMachine classUnderTest = new StateMachine();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
